/* Shared content — single source of truth for services, expertise, etc. */

window.CAPIO_SERVICES = [
  {
    id: "iso-consulting", code: "01", group: "Governance",
    name: "ISO Consulting",
    short: "ISO 27001 · 27701 · 22301 · 9001 · more",
    blurb: "End-to-end ISO consulting across information security, privacy, business continuity, quality, sustainability, and health & safety standards.",
    long: "Capio's ISO practice spans the full landscape of ISO standards relevant to Indonesian enterprises &mdash; from information security and resilience (27001 family), through privacy (27701/29100), governance and continuity (37001/22301), quality and service management (9001/20000), to sustainability and verification (14001/14064/ISCC). Our Lead Auditors hold active certifications across these tracks, so the same partner can run the whole programme rather than handing you off between specialists.",
    deliverables: ["Gap assessment", "Statement of Applicability", "Control implementation", "Internal audit & cert support"],
    duration: "3–18 months", teamSize: "3–6 senior",
    bullets: ["Lead Auditor ISO 27001:2022", "Lead Auditor ISO 22301", "Lead Auditor ISO 20000", "BSSN-registered"],
    featured: true,
  },
  {
    id: "it-audit", code: "02", group: "Regulated Audit",
    name: "IT Audit",
    short: "COBIT 2019 · NIST · PJP2",
    blurb: "Independent IT audits using COBIT 2019 and NIST frameworks &mdash; aligned with BI, OJK, and Kemenkes regulatory expectations.",
    long: "Our auditors are CISA-certified (ISACA & INIXINDO) and registered with BSSN. We deliver audit-grade findings against COBIT 2019, NIST CSF, NIST 800-53, and BI's PJP2 framework &mdash; with evidence packages structured to flow directly into your regulator submission.",
    deliverables: ["Audit plan & scope", "Evidence collection", "Findings & management response", "Regulator submission pack"],
    duration: "4–12 weeks", teamSize: "2–4 senior",
    bullets: ["COBIT 2019", "NIST CSF", "BI PJP2", "OJK SE 21"],
  },
  {
    id: "security-tech", code: "03", group: "Offensive Security",
    name: "Security Technology",
    short: "VAPT · Hardening · Awareness",
    blurb: "Vulnerability Assessment & Penetration Testing, server hardening programmes, and organisation-wide security awareness training.",
    long: "Our offensive team holds OSCP, OSWP, CEH, ECSA, LPT, CHFI and Advanced Penetration Testing certifications. We deliver multi-target VAPT scoped to your real threat model &mdash; web, API, mobile, internal, and cloud &mdash; plus server hardening baselines (CIS) and awareness programmes that actually shift behaviour.",
    deliverables: ["VAPT executive report", "Technical findings & PoC", "Hardening baselines", "Awareness curriculum"],
    duration: "2–8 weeks", teamSize: "2–4 senior",
    bullets: ["OSCP / OSWP", "CEH / ECSA / LPT", "CIS Benchmarks", "OWASP ASVS"],
  },
  {
    id: "soc", code: "04", group: "Managed",
    name: "Security Operation Center",
    short: "Customised SOC-as-a-Service",
    blurb: "SOC service with a customisation model built around your existing tooling, staffing reality, and regulatory environment.",
    long: "We don't sell a one-size SOC. We assess your existing telemetry, detection coverage, and incident response capability, then design a SOC model that fills the gaps &mdash; from 8&times;5 triage to 24&times;7 hunt. Includes incident handler-led playbooks (ECIH, CSIRT certifications from SEI Carnegie Mellon, RCS S.p.A).",
    deliverables: ["SOC design memo", "Detection coverage map", "Playbooks & runbooks", "Monthly reporting cadence"],
    duration: "Ongoing · 6+ months", teamSize: "4–10",
    bullets: ["ECIH-led IR", "SEI/CMU-trained CSIRT", "OpenEDR-aware", "BSSN coordination"],
  },
  {
    id: "manpower", code: "05", group: "Staffing",
    name: "IT Manpower Services",
    short: "Contract-based IT staffing",
    blurb: "Provide vetted IT manpower under a contract service model &mdash; from individual specialists to embedded delivery teams.",
    long: "When your headcount budget says no but your roadmap says yes. We place vetted senior practitioners on contract, with quarterly performance reviews and a named Capio partner who stays accountable for delivery quality.",
    deliverables: ["Vetted candidate slate", "Contract & onboarding", "Quarterly QA review", "Replacement guarantee"],
    duration: "3 months – multi-year", teamSize: "Scaled to need",
    bullets: ["Vetted seniors", "Quarterly QA", "Replacement guarantee", "NDA-clean handover"],
  },
  {
    id: "software", code: "06", group: "Build",
    name: "Software Development",
    short: "Custom · Web · Mobile · Cloud",
    blurb: "Custom software development &mdash; web apps, mobile apps, API integration, cloud solutions, enterprise systems, modernisation, Agile delivery.",
    long: "Multi-language engineering teams running Scrum (Scrum Foundation certified PMs). We've delivered enterprise modernisation across financial services and healthcare, custom web/mobile platforms, API integration to core banking systems, and cloud migrations on AWS/GCP/Azure.",
    deliverables: ["Discovery & architecture", "Sprint demos", "Production deployment", "Handover & maintenance"],
    duration: "8 weeks – 12 months", teamSize: "4–12",
    bullets: ["Agile / Scrum", "Multi-language", "Cloud-native", "Enterprise modernisation"],
  },
  {
    id: "training", code: "07", group: "Capability",
    name: "Training & Certification",
    short: "IT · Cyber · Operational",
    blurb: "Training and certification programmes across IT, manufacturing operational disciplines, and digital resilience for government officials.",
    long: "Capio is a registered training provider for BSSN-aligned auditor pathways, and our team has been engaged by JICA, Kominfo Digital Talent, and FH UI to deliver training to government officials. We can stand up bespoke programmes for your team or place individuals on our open curriculum.",
    deliverables: ["Curriculum design", "Live cohort delivery", "Assessment & certification", "Post-programme support"],
    duration: "1–12 weeks per cohort", teamSize: "1–3 instructors",
    bullets: ["BSSN-aligned", "JICA-delivered", "Kominfo DTS", "FH UI partnered"],
  },
  {
    id: "it-consultant", code: "08", group: "Advisory",
    name: "IT Consultant",
    short: "Advisory · Technology & Information",
    blurb: "Strategic IT consulting on technology selection, information architecture, and digital transformation &mdash; framework-aligned, vendor-independent.",
    long: "Senior advisory on the questions that fall between the cracks: which framework actually applies, whether to buy or build, how to sequence a multi-year transformation, what evidence your regulator will accept. We're vendor-independent &mdash; our only product is judgement.",
    deliverables: ["Advisory memo", "Board-ready brief", "Vendor evaluation", "Implementation roadmap"],
    duration: "2–12 weeks", teamSize: "1–3 senior",
    bullets: ["Vendor-independent", "Framework-aligned", "Board-ready", "Roadmap-driven"],
  },
];

/* The wheel: ISO consultant expertise domains */
window.CAPIO_ISO_WHEEL = [
  { id: "infosec",      label: "Information Security & Resilience", standards: ["ISO/IEC 27001", "ISO/IEC 27032", "ISO/IEC 27017", "ISO/IEC 27018", "ISO/IEC 20000-1"] },
  { id: "privacy",      label: "Privacy Data Protection",           standards: ["ISO/IEC 27701", "ISO/IEC 29100", "ISO/IEC 29134"] },
  { id: "grc",          label: "Governance, Risk & Compliance",     standards: ["ISO 31000", "ISO 37001", "ISO 22301", "ISO 30301"] },
  { id: "quality",      label: "Quality & Service Management",      standards: ["ISO 9001", "ISO 21001", "ISO 55001", "ISO 21500", "ISO 19650"] },
  { id: "health",       label: "Health & Safety",                   standards: ["ISO/IEC 45001", "ISO/IEC 39001"] },
  { id: "sustain",      label: "Sustainability",                    standards: ["ISO/IEC 14001", "ISO/IEC 50001", "ISCC (Sustainability & Carbon)"] },
  { id: "verification", label: "Verification",                      standards: ["ISO 14064-1", "ISO 14064-2", "ISO 26001", "ESG"] },
];

/* Team expertise — 4 categories from screenshot */
window.CAPIO_EXPERTISE = [
  {
    id: "professional", title: "Professional Certifications & Roles",
    items: [
      "CISA Certified — Certified Information Systems Auditor (ISACA)",
      "Certified Information Systems Auditor based on CISA (INIXINDO)",
      "Fintech Director — Certified by AFPI",
      "Lead Auditor ISO 27001:2022",
      "Lead Auditor ISO 27001:2013",
      "Lead Auditor ISO 20000:2011",
      "Lead Auditor ISO 22301",
      "Lead Auditor Registered BSSN",
      "Project Management Program",
      "Scrum Foundation Professional Certificate",
    ],
  },
  {
    id: "cybersecurity", title: "Cybersecurity & Information Security",
    items: [
      "Certified Ethical Hacker (CEH) — EC-Council",
      "EC-Council Certified Security Analyst: Penetration Testing (ECSA)",
      "Certified in Advanced Penetration Testing — EC-Council",
      "Licensed Penetration Tester (LPT) — EC-Council",
      "Certified Incident Handler (ECIH) — EC-Council",
      "Computer Hacking Forensic Investigator (CHFI) — EC-Council",
      "Offensive Security Certified Professional (OSCP)",
      "Offensive Security Wireless Professional (OSWP)",
      "Cybersecurity (Microsoft)",
      "Cybersecurity Essentials — Cisco",
      "Cyber Security Analyst for Public Sector — Kominfo DTS",
      "Defense Practice Against Cyber Attacks — JICA",
      "Creating & Managing a CSIRT — SEI, Carnegie Mellon",
      "Cyber Security Operation Center — RCS S.p.A",
      "Incident Handler — Spentera",
    ],
  },
  {
    id: "frameworks", title: "Cybersecurity Frameworks & Tools",
    items: [
      "Critical Infrastructure Protection — OPSWAT",
      "OpenEDR — Xcitium",
      "Google Cybersecurity Specialization — Google / Coursera",
      "OIC-CERT 5G and Cloud Security Framework",
    ],
  },
  {
    id: "audit-resilience", title: "Audit & Digital Resilience",
    items: [
      "Information Security Auditor Assistant — BNSP",
      "Training of Trainers: Digital Resilience & Cyber Security for Government Officials — FH UI",
    ],
  },
];

/* — Clients by sector — extracted from existing portfolio screenshots.
   Keep this as a single flat structure: easy to feed from a CMS later. */
window.CAPIO_CLIENTS = [
  { sector: "Financial Business",            sectorShort: "BFSI",     featured: true,
    items: [
      "MNC Leasing", "hibank", "NOBU National Bank", "BCA Multifinance", "MNC Bank",
      "ALTO", "Home Credit", "OK! P2P", "BinaArtha", "IAF Multi Finance",
      "Kredit Pintar", "Kredit Plus", "Singa Fintech", "Samir", "Danafix",
      "Samakita", "Prospera", "Motion Credit", "PT Digital Bertahan Indonesia",
    ],
  },
  { sector: "Investment & Crypto",           sectorShort: "Trading", featured: true,
    items: [
      "Tokocrypto", "Koinsayang", "COINX", "Astal", "D3 Labs",
      "Sentra Arta Maxima", "Realtime Forex Indonesia", "Pan Emperor", "Mentari Mulia Berjangka",
      "MRG Mega Berjangka", "Victory International Futures", "Maxco", "SagaFX (SFX)",
      "Cyber Futures Forex", "Fintech Maju Berjangka", "IndoGold", "MagnetFX",
      "Mahadana Asta Berjangka", "ASIAPRO",
    ],
  },
  { sector: "Asset Management & Securities", sectorShort: "AM/Sec",
    items: [
      "Juara Kelola Dana", "Syailendra", "Purwanto Asset Management", "Mirae Asset",
      "Vestora", "Fund Grow", "Danamart", "EKUID", "Kfund", "Joinan",
      "Sarana Energi Investama", "Kerjasama", "SeedFund", "JOINPROP.ID", "Shafiq",
      "Angel Investor Indonesia", "Venture Hub", "Lotus Andalan Sekuritas", "Investindo",
      "Universal Broker Indonesia Sekuritas", "Buana Capital", "Anugerah Sekuritas Indonesia",
    ],
  },
  { sector: "Payment Gateway & Remittance",  sectorShort: "Payments",
    items: [
      "PayCools", "GPay", "MotionPay", "Duwit", "ZiPay", "Singa Pay", "FINPOINT", "Transforce",
    ],
  },
  { sector: "Financial Ecosystem & Aggregator", sectorShort: "Aggregator",
    items: ["Pilih Kredit", "Aiskor", "Redit List"],
  },
  { sector: "Insurance Business",            sectorShort: "Insurance", featured: true,
    items: [
      "Taspen Life", "HEKSA Insurance", "Reliance Life", "AUS (Asuransi Untuk Semua)",
      "Futureready", "PasarPolis",
    ],
  },
  { sector: "Government Sector",             sectorShort: "Government", featured: true,
    items: [
      "DKPPU", "JOB Pertamina-Medco E&P Tomori Sulawesi", "RSUD Dr. Soedarso Pontianak",
      "Otorita Ibu Kota Nusantara", "PT Wijaya Karya (WIKA)", "RSJ Provinsi Kalimantan Barat",
    ],
  },
  { sector: "Technologies Business",         sectorShort: "Technology",
    items: [
      "PT Wira Arta Telematika", "GTECH", "IDstar", "TechData", "Akar Inti Data",
      "Digital Teknologi Indonesia", "CODR", "Compute (Re:Invent Go:Beyond)", "Q2 Technologies",
      "Giszilla", "PT Teknologi Internasional Nusantara (TIN)", "Delman Data Lab",
      "PT Jaga Anugrah Giat Asa", "MNC Vision Networks (MVN)", "Digital Daya Teknologi",
    ],
  },
  { sector: "Manufacture Business",          sectorShort: "Manufacturing",
    items: [
      "Combiphar", "Komatsu", "PT Tracon Industri", "Skyworth", "PT YKK Zipper Indonesia",
      "YKK AP", "Mitra Prodin", "Kubota", "Teikin Engine Components", "Unza Vitalis",
      "Indo Taichen Textile Industry",
    ],
  },
  { sector: "Media & Information",           sectorShort: "Media",
    items: ["Gramedia Digital", "RCTI", "Zomato", "Investor Daily", "Gramedia", "GTV"],
  },
  { sector: "Education",                     sectorShort: "Edu",
    items: ["Bina Nusantara", "LPK Edukasi Reksa Manajemen", "Omarco", "Sekolah.mu"],
  },
  { sector: "E-Commerce",                    sectorShort: "E-com",
    items: ["Sephora", "Luxola", "Atome", "Tokoplas"],
  },
  { sector: "Others Business",               sectorShort: "Others",
    items: ["PT Krazu Nusantara", "BUMA (Bukit Makmur Mandiri Utama)", "Gudangada", "Gapura Airport Services"],
  },
];

/* — Certifications & accreditations Capio has obtained — */
window.CAPIO_CERTS = [
  { id: "iso27001",   org: "ISO",           code: "ISO 27001:2022", label: "Lead Auditor",                   color: "#2D4A6B", year: "Active" },
  { id: "iso22301",   org: "ISO",           code: "ISO 22301",      label: "Business Continuity LA",         color: "#2D4A6B", year: "Active" },
  { id: "iso20000",   org: "ISO",           code: "ISO 20000",      label: "Service Management LA",          color: "#2D4A6B", year: "Active" },
  { id: "iso27701",   org: "ISO",           code: "ISO 27701",      label: "Privacy Management",             color: "#2D4A6B", year: "Active" },
  { id: "cisa",       org: "ISACA",         code: "CISA",           label: "Certified IS Auditor",           color: "#7A4A1E", year: "Active" },
  { id: "cisa-inix",  org: "INIXINDO",      code: "CISA",           label: "Auditor based on CISA",          color: "#7A4A1E", year: "Active" },
  { id: "bssn",       org: "BSSN",          code: "BSSN",           label: "Registered Auditor",             color: "#234E3B", year: "Active" },
  { id: "afpi",       org: "AFPI",          code: "Fintech Dir.",   label: "Fintech Director",               color: "#234E3B", year: "Active" },
  { id: "oscp",       org: "Offensive Sec", code: "OSCP",           label: "Penetration Tester",             color: "#1F2430", year: "Active" },
  { id: "oswp",       org: "Offensive Sec", code: "OSWP",           label: "Wireless Professional",          color: "#1F2430", year: "Active" },
  { id: "ceh",        org: "EC-Council",    code: "CEH",            label: "Ethical Hacker",                 color: "#6E2A2A", year: "Active" },
  { id: "ecsa",       org: "EC-Council",    code: "ECSA",           label: "Security Analyst · Pentest",     color: "#6E2A2A", year: "Active" },
  { id: "lpt",        org: "EC-Council",    code: "LPT",            label: "Licensed Penetration Tester",    color: "#6E2A2A", year: "Active" },
  { id: "ecih",       org: "EC-Council",    code: "ECIH",           label: "Incident Handler",               color: "#6E2A2A", year: "Active" },
  { id: "chfi",       org: "EC-Council",    code: "CHFI",           label: "Forensic Investigator",          color: "#6E2A2A", year: "Active" },
  { id: "cmu-csirt",  org: "SEI · CMU",     code: "CSIRT",          label: "Creating & Managing a CSIRT",    color: "#3A2A5E", year: "Trained" },
  { id: "bnsp",       org: "BNSP",          code: "BNSP",           label: "Info-Sec Auditor Assistant",     color: "#234E3B", year: "Active" },
  { id: "kominfo",    org: "Kominfo DTS",   code: "DTS",            label: "Cyber Analyst · Public Sector",  color: "#234E3B", year: "Trained" },
  { id: "jica",       org: "JICA",          code: "JICA",           label: "Defense vs Cyber Attacks",       color: "#3A2A5E", year: "Trained" },
  { id: "rcs-soc",    org: "RCS S.p.A",     code: "SOC",            label: "Cyber Security Ops Center",      color: "#3A2A5E", year: "Trained" },
  { id: "opswat",     org: "OPSWAT",        code: "CIP",            label: "Critical Infrastructure Prot.",  color: "#1F2430", year: "Partner" },
  { id: "xcitium",    org: "Xcitium",       code: "OpenEDR",        label: "Endpoint Detection",             color: "#1F2430", year: "Partner" },
];

/* — Product case studies (delivered to customers; from existing site /our-portfolios) — */
window.CAPIO_PRODUCT_CASES = [
  {
    id: "nobu-finance",
    client: "NOBU Finance",
    sector: "Banking · Multifinance",
    year: "2024",
    title: "Mobile banking front-end & secure auth flow.",
    summary: "A clean, regulator-aligned mobile login and onboarding experience for NOBU's retail banking customers — built on a hardened auth stack with PJP2-aware audit trails.",
    challenge: "NOBU needed to consolidate three legacy login screens into a single trustworthy mobile experience, while satisfying BI security expectations on session handling, biometric authentication, and audit logging.",
    solution: "Capio's software team rebuilt the onboarding and login experience from scratch, paired with a senior security review on the auth flow. Biometric fallback, device-binding, and a hardened token-refresh loop all map cleanly to PJP2 audit evidence.",
    outcomes: [
      ["Login success rate", "+18%"],
      ["Auth findings (BI)", "0"],
      ["Time-to-onboard", "−42%"],
      ["Release cadence", "Bi-weekly"],
    ],
    services: ["Software Development", "Security Technology", "IT Audit"],
    tag: "Mobile · Auth",
  },
  {
    id: "al-hikmah",
    client: "Al Hikmah · KopLink",
    sector: "Cooperative · Financial",
    year: "2024",
    title: "KopLink — digital cooperative banking experience.",
    summary: "A modern member-facing app for Al Hikmah cooperative: savings, wallet, financing, and commerce features, with shariah-aligned compliance.",
    challenge: "Cooperatives in Indonesia typically have under-served digital UX. Al Hikmah wanted a member-app that felt at least as good as commercial bank apps, while respecting cooperative governance and shariah-compliance rules.",
    solution: "We delivered the full KopLink mobile front-end and integrated it to the cooperative's core systems via secured APIs. Capio's audit team reviewed the segregation of duties and shariah compliance touch points end-to-end.",
    outcomes: [
      ["Active members", "+2.4×"],
      ["App store rating", "4.7★"],
      ["Tx/month", "120K+"],
      ["Findings closed", "100%"],
    ],
    services: ["Software Development", "IT Audit"],
    tag: "Cooperative · App",
  },
  {
    id: "hi-bank",
    client: "Hi Bank",
    sector: "Banking",
    year: "2024",
    title: "Financial Supply Chain Management portal.",
    summary: "A B2B portal for Hi Bank's Financial Supply Chain Management line — onboarding, financing requests, and reconciliation, on a hardened cloud stack.",
    challenge: "Hi Bank needed a corporate-facing platform that could absorb high-volume invoice and financing workflows from multiple anchor corporates, with strict OJK alignment.",
    solution: "Capio designed and built the FSCM portal end-to-end, including identity, document handling, reconciliation engine, and audit pipeline. ISO 27001-aligned controls were embedded at design time, not retrofitted.",
    outcomes: [
      ["Anchor corporates", "12"],
      ["Onboarding time", "−65%"],
      ["OJK findings", "0"],
      ["SLA achievement", "99.95%"],
    ],
    services: ["Software Development", "ISO Consulting", "IT Audit"],
    tag: "B2B · FSCM",
  },
  {
    id: "mnc-motion",
    client: "MNC Motion · MotionPaylater",
    sector: "Fintech · BNPL",
    year: "2023–2024",
    title: "MotionPaylater — paylater wallet & credit experience.",
    summary: "Mobile-first paylater product for MNC's user base, with bill-pay, instalment, and credit-limit UX patterns that survive Bank Indonesia scrutiny.",
    challenge: "Paylater UX is regulator-sensitive — credit-limit display, instalment disclosures, and overdue handling all have BI expectations. MNC needed a product team that could move fast without earning enforcement attention.",
    solution: "Our software practice built the MotionPaylater mobile front-end; the audit practice ran a parallel BI-aligned review of every screen. Every credit disclosure was reviewed and signed off by a Lead Auditor before release.",
    outcomes: [
      ["Limit utilisation", "+31%"],
      ["BI enforcement", "None"],
      ["Bill payment GMV", "Rp 1.6T+"],
      ["App rating", "4.6★"],
    ],
    services: ["Software Development", "IT Audit", "Security Technology"],
    tag: "Paylater · Wallet",
  },
  {
    id: "mnc-credit",
    client: "MNC Credit",
    sector: "Fintech · Credit",
    year: "2024",
    title: "QRIS-integrated credit & limit management.",
    summary: "A mobile credit product for MNC, integrated with QRIS, with clear limit visualisation and reconciliation that matches BI's PJP2 expectations.",
    challenge: "QRIS-integrated credit products are still a relatively new category in Indonesia. MNC Credit needed a UX that made limits and usage radically clear to the user, while feeding clean evidence into the audit log.",
    solution: "We built the front-end and the reconciliation pipeline, then ran a PJP2 mini-audit on the live flows before launch. The limit visualisation became internal best-practice across other MNC fintech products.",
    outcomes: [
      ["First-month users", "180K"],
      ["Default rate", "Below sector"],
      ["QRIS tx", "9M/mo"],
      ["Audit pass", "First review"],
    ],
    services: ["Software Development", "IT Audit"],
    tag: "QRIS · Credit",
  },
  {
    id: "bca-multifinance",
    client: "BCA Multifinance",
    sector: "Multifinance",
    year: "2023",
    title: "Internal audit modernisation & evidence pipeline.",
    summary: "Modernised BCA Multifinance's internal audit programme with an evidence pipeline that flows directly into OJK submission packages.",
    challenge: "BCA Multifinance's internal audit team was generating high-quality findings but losing time on evidence collation. Each audit cycle was running over budget on administrative effort.",
    solution: "Capio's audit practice redesigned the internal audit playbook around an evidence-first pipeline, with COBIT 2019-aligned control mapping. The result feeds directly into OJK reporting without re-keying.",
    outcomes: [
      ["Audit cycle time", "−38%"],
      ["Evidence re-collection", "−72%"],
      ["OJK findings", "0 major"],
      ["Auditor satisfaction", "+ qualitative"],
    ],
    services: ["IT Audit", "ISO Consulting"],
    tag: "Audit · OJK",
  },
  {
    id: "idstar",
    client: "IDstar",
    sector: "Technology Services",
    year: "2024",
    title: "IT manpower & co-delivery partnership.",
    summary: "A multi-year IT manpower partnership with IDstar — placing vetted senior practitioners on client engagements with Capio's QA standing behind every placement.",
    challenge: "IDstar needed a partner who could supply senior cybersecurity and audit talent at scale without compromising on quality. The market is full of agencies; very few hold their own engagement quality standards.",
    solution: "We placed senior practitioners on IDstar's most demanding engagements, with quarterly QA reviews held jointly. The arrangement is ongoing — Capio's name now sits behind each placement.",
    outcomes: [
      ["Placements", "24+"],
      ["Replacement rate", "< 4%"],
      ["Avg. tenure", "11 mo"],
      ["NPS (joint)", "62"],
    ],
    services: ["IT Manpower Services"],
    tag: "Staffing · Ongoing",
  },
];

/* — Service case studies (consulting engagements) — */
window.CAPIO_SERVICE_CASES = [
  {
    id: "ojk-worldbank",
    client: "OJK · with World Bank",
    sector: "Government · Regulator",
    year: "2024–2025",
    title: "Strengthening OJK Information System (IS) Security Management.",
    summary: "World Bank-funded engagement to assess OJK's information system security maturity and design the standard operating procedures (SOPs) that will govern OJK's IS security going forward.",
    challenge: "As Indonesia's financial services regulator, OJK supervises hundreds of regulated entities — yet its own internal IS security maturity hadn't been independently benchmarked. The World Bank engaged a small bench to deliver an honest, evidence-based picture and then write the SOPs that would set OJK's go-forward standard.",
    solution: "Capio led the gap analysis across OJK's IS estate — assessing controls against ISO 27001:2022, NIST CSF, and OJK's own SE 21 expectations. We then drafted the full SOP set covering access governance, incident response, change management, vendor risk, and data protection. Every SOP was workshopped with OJK directorates before sign-off.",
    outcomes: [
      ["Controls assessed", "180+"],
      ["SOPs delivered", "27"],
      ["Directorates engaged", "9"],
      ["World Bank rating", "Satisfactory"],
    ],
    services: ["ISO Consulting", "IT Audit", "IT Consultant"],
    tag: "Regulator · Featured",
    featured: true,
  },
  {
    id: "mnc-group",
    client: "PT MNC Asia Holding Tbk · MNC Group",
    sector: "Conglomerate · Media / BFSI / Telco",
    year: "2022–present · 3+ years ongoing",
    title: "ISO multi-standard, IT audit, pentest, and ongoing build partner.",
    summary: "A multi-year, multi-discipline engagement with MNC Group spanning ISO 27001, 27701, 37001 implementation, IT audit, penetration testing, software development, and embedded IT manpower.",
    challenge: "MNC Group operates across media, banking, multifinance, and fintech — each business unit has its own threat model, regulatory environment, and technology stack. The group needed a single partner who could hold the whole picture and deliver consistent quality across all of it.",
    solution: "Capio has been embedded across MNC Group for over three years. We've delivered ISO 27001, 27701 (privacy), and 37001 (anti-bribery) implementation programmes across multiple subsidiaries; ongoing IT audit cycles aligned to BI/OJK; recurring penetration testing on consumer-facing products including MotionPaylater and MNC Credit; software development for digital banking products; and IT manpower placements to fill specialist gaps.",
    outcomes: [
      ["Years engaged", "3+ ongoing"],
      ["ISO certifications", "27001 · 27701 · 37001"],
      ["Pentests delivered", "20+"],
      ["Business units served", "9"],
    ],
    services: ["ISO Consulting", "IT Audit", "Security Technology", "Software Development", "IT Manpower Services"],
    tag: "Group · Multi-year",
    featured: true,
  },
  {
    id: "combiphar",
    client: "Combiphar",
    sector: "Pharmaceutical · Manufacturing",
    year: "2024",
    title: "ISO 27001:2022 consulting, certification & Purchasing SOP refresh.",
    summary: "End-to-end ISO 27001:2022 implementation and certification support for Combiphar, plus a parallel Purchasing SOP redesign that fed back into the ISMS.",
    challenge: "Combiphar wanted ISO 27001:2022 certification — but the procurement function's existing SOPs were inconsistent with the controls the ISMS would require. A typical 'certify then fix' sequence would have failed surveillance audits.",
    solution: "We ran the ISO 27001:2022 implementation in parallel with a Purchasing SOP redesign — making sure the procurement controls in the new SOPs satisfied the ISMS at first pass. The certification body found Combiphar's evidence flow notably consistent.",
    outcomes: [
      ["Certification result", "Pass · stage 2"],
      ["Major findings", "0"],
      ["Purchasing SOPs", "Refreshed"],
      ["Duration", "9 months"],
    ],
    services: ["ISO Consulting", "IT Consultant"],
    tag: "Manufacturing · ISO",
    featured: true,
  },
  {
    id: "wika-group",
    client: "WIKA Group · PT Wijaya Karya (Persero) Tbk",
    sector: "Construction · State-owned",
    year: "2023–present",
    title: "Capability build & multi-stream cyber programme.",
    summary: "Long-running capability and assurance programme for WIKA Group: CISA training, DPO training, ISO 27001/27701/20000-1 training, internal audit training, penetration testing, and digital transformation analysis.",
    challenge: "As one of Indonesia's largest state-owned construction enterprises, WIKA needed both immediate cyber assurance and a long-term internal capability build — not just consultants flying in and out, but a sustained programme that left WIKA's own people stronger after we left.",
    solution: "We designed a multi-stream programme: CISA and DPO certification pathways for senior practitioners; Lead Auditor training across ISO 27001, 27701, and 20000-1; an internal audit training stream; recurring penetration tests on critical applications; and digital transformation analysis covering operating model and architecture options.",
    outcomes: [
      ["Trainees certified", "40+"],
      ["Training streams", "7"],
      ["Pentests delivered", "Multiple cycles"],
      ["DX recommendations", "Adopted board-level"],
    ],
    services: ["Training & Certification", "Security Technology", "ISO Consulting", "IT Audit", "IT Consultant"],
    tag: "SOE · Capability",
    featured: true,
  },
];
